### PR TITLE
feat: add disableTimecheck option to pass thru from ceramic

### PR DESCRIPTION
**Pull request by zachferland**

### CODE REVIEW

**Comment by zachferland** [comment]
@ukstv merge/release if you can, i dont have permissions on this package right now

**Comment by oed** [comment]
I assume this caused the bug Orbis observed? Can you add some more context for reviewers?

**Review by ukstv — APPROVED** [review]

**Comment by ukstv** [comment]
Yes @oed , it is about Orbis-reported bug.

**Comment by ukstv** [comment]
On a second thought, IMO, we should rename `disableTimecheck` with `disableExpirationCheck` or something to signify that it only applies to `expiration-time` field.

**Pull request merged**
